# Generated by Django 4.1.4 on 2023-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
