# Generated by Django 4.1.4 on 2023-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_contactus_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
