# Generated by Django 4.1.4 on 2023-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_contactus_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Owner"),
                    (2, "Vendor"),
                    (3, "Agent"),
                    (4, "Subagent"),
                    (5, "Tenent"),
                    (6, "Associate"),
                ],
                null=True,
            ),
        ),
    ]
