# Generated by Django 4.1.4 on 2023-02-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expads", "0001_initial"),
    ]

    operations = []
